name: seek-prueba-tecnica
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - seek-customer:/var/lib/mysql
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  spring-boot-app:
    image: mi-aplicacion:latest
    container_name: spring-boot-app
    ports:
      - "8080:8080"

volumes:
  seek-customer: